runtime: java18
entrypoint: 'java -jar librarybackend-0.0.2-SNAPSHOT.jar'

spring:
  datasource:
    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net:3306/heroku_ac6fbcff06c2e36
    username: beb7489dc69705
    password: fdc02e11
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifetime: 20000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

mail:
  smtp:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    ssl: false
    tls: true
    username: fedb6db92c0160
    password: d9e79b0eada78c
    auth: true
    starttls:
      enable: true
