name: Maven Package

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests and generate JaCoCo code coverage
      run: mvn test jacoco:report

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true

    - name: Run OWASP Dependency-Check
      run: mvn org.owasp:dependency-check-maven:check
    
    - name: Clean untracked files and directories
      run: git clean -f -d

    - name: Switch to gh-pages branch
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git fetch
        git checkout gh-pages

    - name: Copy dependency-check report to root
      run: cp target/dependency-check-report.html .

    - name: Commit and push the report
      run: |
        git add dependency-check-report.html
        git commit -m "Update dependency-check report"
        git push origin gh-pages
